name: VirtualLeaf compile, clean, and package for macOS (arm)
run-name: ${{ github.actor }} is testing on macOS (arm) 🚀

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2' # Specify the required Qt version
        host: 'mac'
        target: 'desktop'

    - name: Configure Project with qmake
      run: |
        cd src
        qmake CONFIG+=c++14 VirtualLeaf.pro -early QMAKE_DEFAULT_LIBDIRS=$(xcrun -show-sdk-path)/usr/lib

    - name: Build Project
      run: |
        cd src
        make

    - name: Deploy Qt Frameworks
      run: |
        cd src/bin
        macdeployqt VirtualLeaf.app
        otool -L VirtualLeaf.app/Contents/MacOS/VirtualLeaf
    
    - name: Package Project
      uses: actions/upload-artifact@v4
      with:
        name: VirtualLeaf-macos-arm
        path: |
          ${{ github.workspace }}/bin/**/*
          ${{ github.workspace }}/data/**/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install
      run: sudo apt-get install zip gzip
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R ${{ github.workspace }}

    - name: '📦 Package MacOS arm'
      if: github.event_name == 'release' && github.event.action == 'created'
      run: |
        zip -r VirtualLeaf-macos-arm.zip VirtualLeaf-macos-arm
        gh release upload ${{github.event.release.tag_name}} VirtualLeaf-macos-arm.zip        
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash



